

""""" pathogen stuff 
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
filetype off


filetype plugin indent on     " Required!


"""""" My Stuff 
syntax on
set rnu
set ruler
set cursorline
set cursorcolumn
let &colorcolumn=join(range(80,99),",")
colorscheme lucius
LuciusBlackHighContrast


" indentation stuffs
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smarttab

" unite.vim stuff
nnoremap <leader>f :<C-u>Unite -no-split -buffer-name=files   -start-insert file<cr>
nnoremap <leader>b :<C-u>Unite -no-split -buffer-name=buffer  buffer<cr>
