

""""" vundle stuff 
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'


""""" my bundles from github
Bundle 'Shougo/unite.vim'


filetype plugin indent on     " Required!


"""""" My Stuff 
syntax on
set rnu
set ruler
set cursorline
set cursorcolumn
let &colorcolumn=join(range(80,99),",")
"colorscheme flatcolor


" indentation stuffs
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smarttab

